shell = "zsh"

[plugins]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# syntax highlighting 系は最後に読み込む
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
